{
    'name': 'Grocery Management',
    'version': '1.0',
    'category': 'Sales',
    'summary': 'Manage grocery products, customers and sales',
    'author': 'Hithesh',
    'license': 'LGPL-3',
    'depends': ['base', 'sale', 'stock', 'mail'],
    'data': [
        'security/grocery_groups.xml',
        'security/ir.access.csv',
        'security/grocery_security.xml',
        'views/grocery_restock_wizard_views.xml',
        'views/grocery_product_views.xml',
        'views/grocery_product_menu.xml',
        'views/grocery_customer_views.xml',
        "views/grocery_sale_views.xml",
        'views/res_config_settings_views.xml',
        'data/grocery_sequence.xml',
        'data/grocery_automation.xml',
    ],
    'installable': True,
    'application': True,
}